export const site = {
  name: "Lewis Munro",
  email: "studio@lewismunro.com",
  instagram: "https://www.instagram.com/lewismunro_/",
  bio: "Lewis Munro is a fashion stylist and consultant, based in London, working internationally with a diverse client base spanning across editorial, commercial, and celebrity projects.",
  clients: [
    "Prada",
    "Gucci Beauty",
    "ON",
    "Nike",
    "Burberry",
    "H&M",
    "Mercedes Benz",
    "Dr Martens",
    "Jordan",
    "Asics",
    "Levis",
    "Ugg",
    "Westfield",
    "Chivas",
    "Reebok",
    "Flannels",
    "Visa Cash App Redbull (VCARB)",
    "EA Sports",
    "Sony Virgin EMI",
  ],
  publications: [
    "Glass Magazine",
    "Vogue Italia",
    "Vogue Portugal",
    "GQ Style",
    "TANK",
    "Dazed Beauty",
    "Highsnobiety",
    "Hypebeast",
    "Grazia",
    "Paper Magazine",
  ],
};
